// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK7mP5vAv7nZID-brOCqMwWrcJ1wYW0Qg',
    appId: '1:462525810870:web:2120e523e591daff043e17',
    messagingSenderId: '462525810870',
    projectId: 'study-app-f8905',
    authDomain: 'study-app-f8905.firebaseapp.com',
    storageBucket: 'study-app-f8905.appspot.com',
    measurementId: 'G-E7Y3C86ZHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3KGs6c3cuvvLnYPCs0Cw6T-vO-2ij6A4',
    appId: '1:462525810870:android:79548053f820d91a043e17',
    messagingSenderId: '462525810870',
    projectId: 'study-app-f8905',
    storageBucket: 'study-app-f8905.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzaqq8ZHhiie3gKXQ1336BW3a5ZGImDdA',
    appId: '1:462525810870:ios:007cea15e7ccd2f7043e17',
    messagingSenderId: '462525810870',
    projectId: 'study-app-f8905',
    storageBucket: 'study-app-f8905.appspot.com',
    iosClientId: '462525810870-skf3se5893f6ijt4d26a83h48ucvdo6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mountain',
  );
}
